services:
  - type: web
    name: guvi-task-app
    env: docker
    plan: free
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: guvi-task-redis
          property: connectionString
      - key: MYSQL_URL
        sync: false
      - key: MONGODB_URI
        sync: false

  - type: redis
    name: guvi-task-redis
    plan: free 
    ipAllowList: [] 
